spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui-custom.html